language: java
sudo: false
jdk: openjdk8

before_install:
  - unset TRAVIS
  - unset _JAVA_OPTIONS
  - wget http://www.deflaker.org/maven/apache-maven-3.5.0.zip
  - unzip -qq apache-maven-3.5.0.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH

install: mvn ${SPARK} -Ptravis -Pnetlib -DskipTests=true -nsu -B install
script:
  - mvn ${SPARK} ${JACOCO} -Ptravis -Pnetlib -q -nsu -B verify
  - find $HOME/.m2/repository/com/cloudera/oryx -path "*SNAPSHOT/*" -delete
  - find $HOME/.m2/repository/com/cloudera/oryx -name "*SNAPSHOT" -type d -delete
env: JACOCO=-Pjacoco FIREBASE_KEY=AIzaSyDU7I6pnN322BvRNN24jRX52owAvuHH1K4

cache:
  directories:
    - $HOME/.m2
git:
  depth: 10
after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi
